# Generated by Django 3.1.7 on 2021-07-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('android_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ios_id', models.CharField(blank=True, max_length=128, null=True)),
                ('support_region', models.IntegerField()),
                ('project_logo', models.FileField(default='imgs/app_review_project/Neulion.png', upload_to='imgs/app_review_project')),
                ('android_origin', models.CharField(blank=True, max_length=256, null=True)),
                ('ios_origin', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('review_id', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=256)),
                ('platform', models.IntegerField(choices=[(0, 'Android'), (1, 'iOS')])),
                ('country', models.CharField(max_length=36)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_appstore_reviews.project', to_field='project_name')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDetail',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, null=True)),
                ('content', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('version', models.CharField(max_length=12, null=True)),
                ('review_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='google_appstore_reviews.reviewinfo')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
