# Generated by Django 3.1.7 on 2021-07-08 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('logo', models.FileField(default='imgs/testcase/Neulion.png', upload_to='imgs/testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('allure_report_url', models.CharField(max_length=256)),
                ('testcases_total', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('failed', models.IntegerField()),
                ('error', models.IntegerField()),
                ('skipped', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passing_rate', models.CharField(max_length=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='testcase name', max_length=64)),
                ('node_id', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='testcase description')),
                ('classification', models.CharField(choices=[('web', 'WEB'), ('iOS', 'IOS'), ('Android', 'ANDROID'), ('Api', 'API')], default='web', max_length=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.project')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('job_name', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_execute', models.DateTimeField(blank=True, null=True)),
                ('execute_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.project')),
                ('testcase', models.ManyToManyField(to='testcase_management.Testcase')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecuteRecord',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128)),
                ('build_id', models.IntegerField()),
                ('build_url', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testcase_management.report')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.testtask', to_field='name')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
