# Generated by Django 3.1.7 on 2021-07-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0002_auto_20210708_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecuterecord',
            name='build_url',
            field=models.CharField(max_length=245, unique=True),
        ),
    ]
