# Generated by Django 3.1.7 on 2021-07-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0003_auto_20210708_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecuterecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.testtask'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='testtask',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='testtask_unique_task_name'),
        ),
    ]
