# Generated by Django 3.1.7 on 2021-07-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('scheme', models.CharField(max_length=64, verbose_name='Prefix Name')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=128, verbose_name='Deeplink Detail')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('classification', models.CharField(default='Default', max_length=32, verbose_name='Classification')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deeplink.project', verbose_name='Project Name')),
            ],
        ),
    ]
