# Generated by Django 3.1.7 on 2021-07-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Project Name')),
                ('scheme', models.CharField(max_length=40, verbose_name='Project Scheme')),
                ('api_key', models.CharField(max_length=128, verbose_name='API Key')),
                ('instance_url', models.CharField(max_length=128, verbose_name='Notification Server Url')),
            ],
        ),
        migrations.CreateModel(
            name='SdkConifg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=128)),
                ('config_type', models.CharField(max_length=32)),
                ('app_key', models.CharField(max_length=218, unique=True)),
            ],
            options={
                'ordering': ['-nid'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('push_type', models.IntegerField(choices=[(0, 'PUSH_TYPE'), (1, 'deeplink'), (2, 'general')], verbose_name='Notification Type')),
                ('content', models.CharField(max_length=128, verbose_name='Notification Content')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_tools.project', verbose_name='Project Name')),
            ],
            options={
                'ordering': ['-nid'],
            },
        ),
    ]
